language: generic 
sudo: required 
services:
  - docker

before_install: 
  - docker build -t jparrish62/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jparrish62/docker-react npm run test
deploy:  
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-187861951944"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
